# Solarized-luv color palette
set -l foreground 839496
set -l selection 083046
set -l comment 586e75
set -l red fb322d
set -l orange f55c1d
set -l yellow f7bc00
set -l green a0b800
set -l baseblue 268bd2
set -l blue 32a6f9
set -l pink ff1a97

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $baseblue
set -g fish_color_keyword $pink
set -g fish_color_quote $yellow
set -g fish_color_redirection $foreground
set -g fish_color_end $orange
set -g fish_color_option $pink
set -g fish_color_error $red
set -g fish_color_param $blue
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $pink
set -g fish_color_autosuggestion $comment

# Completion Pager Colors
set -g fish_pager_color_progress $comment
set -g fish_pager_color_prefix $baseblue
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
set -g fish_pager_color_selected_background --background=$selection
